{% set name = "python-box" %}
{% set version = "7.1.1" %}
{% set sha256 = "05e38713932906f86eac7411fcc1c6a9231fee5fac8c1c6ce64acc362feb8340" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdgriffith/Box/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # python 3.12 causes segmentation fault in tests.
  skip: True  # [py==312]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
  run_constrained:
    - msgpack-python >=1.0.0
    - ruamel.yaml >=0.17

test:
  source_files:
    - test
  imports:
    - box
  commands:
    - pip check
    # skipping test due to not having msgpack. Skipping other tests that require it.
    # - pytest -v test --ignore=test/test_converters.py -k "not test_from_all" # [not s390x]
    # - pytest -v test --ignore=test/test_converters.py -k "not (test_from_all or test_to_yaml_file)" # [s390x]
    - pytest -v test
  requires:
    - msgpack-python >=1.0.0
    - pip
    - pytest >=7.1.3
    - ruamel.yaml >=0.17
    - tomli >=1.2.3  # [py<311]
    - tomli-w >=1.0.0

about:
  home: https://github.com/cdgriffith/Box
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python dictionaries with recursive dot notation access
  description: |
    Box is designed to be an easy drop in transparently replacements for dictionaries, 
    thanks to Python’s duck typing capabilities, which adds dot notation access. Any sub 
    dictionaries or ones set after initiation will be automatically converted to a Box 
    object. You can always run .to_dict() on it to return the object and all sub objects 
    back into a regular dictionary.
  doc_url: https://github.com/cdgriffith/Box
  dev_url: https://github.com/cdgriffith/Box

extra:
  recipe-maintainers:
    - jan-janssen
    - cdgriffith
