{% set name = "python-box" %}
{% set version = "3.4.6" %}
{% set sha256 = "694a7555e3ff9fbbce734bbaef3aad92b8e4ed0659d3ed04d56b6a0a0eff26a9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - box

about:
  home: https://github.com/cdgriffith/Box
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Python dictionaries with recursive dot notation access'
  description: |
    Box is designed to be an easy drop in transparently replacements for dictionaries, 
    thanks to Python’s duck typing capabilities, which adds dot notation access. Any sub 
    dictionaries or ones set after initiation will be automatically converted to a Box 
    object. You can always run .to_dict() on it to return the object and all sub objects 
    back into a regular dictionary.
  doc_url: https://github.com/cdgriffith/Box
  dev_url: https://github.com/cdgriffith/Box

extra:
  recipe-maintainers:
    - jan-janssen
    - cdgriffith
