travis:
  secure:
    BINSTAR_TOKEN: I9c/RjxQ5nt2gZdX6UE0UACWfy3cx1Yi93+RnJd33AzPcyVCqjtBpXPc/c7fM7U1z+keMO3nI63HUBOe6VO8lovIjIFxcF/zM1fozv07vPto5ACHblqCQ5bd7EsDoDJ3QyxG30Hdym4hrQOrnQaYs60uheqTAFKm2QtCCU1vG7wC6wscFIy7OgL5rMDCEWQzPqlLlh/xyRdmDdUWmlSLAaoiNKidJHOg0PsJevrlASEhEBVVUvCZoRwO+nd2OPr6fdFAve0kP/KSmblFxQlGOBfz/AUYXy/KEXJQ+k2RuavyT+SlRBBsJhjbVhekFQ5JUrP8JWzvuiQTKAy8Lzd4OJ16te8zmm+QBuxubNiNHh35hRr8zaYs/4d+q1F9wuCERfijqIIv/oF1+idezGwzDkOpgzmAiRFylz9WPobvfUWC1QK7awkjBOhucoQWPlX9zvq96M1U1BwXODT6JeU+s3uChS52XT34F2833VrpFsxjk0nhed5WbxyVglt1B6HThmvay2lafXBUKAgpRmGYGpzr62mWY6YPDpWxoXvNMGJgAqUR/4v0lLmgZNmK4YUT3dQ+H73o59SWMvndjCWnraIoeruTt0atPDoPL5q4ACZxAg26eUmB1hqcOpAZhWwRdO5hEKxLTTs2lUxH6mWWSFS2SlhMOiVXXd8o1Uj3lsc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
