travis:
  secure:
    BINSTAR_TOKEN: n7yGyuwO+MkWmZx9EEa1/7RIFSPTtKHdl5Z92BiPTdTNP7JPiXrk9Ptzu+7b40CdTVpev24iWnm9IodDZiJw8zrGqjFPgdWKANgvwxCTL0yzkv0bySr151L4P5FUPEhtyj4zXSRuvsgIWQ7FIl6DB9jZ/D9ua1IgR3SztdRCaXxM7tGc1yBC1r5mgic92Eiwb+wYetsAkjrB3MaW1J5qqZF3PuhDn8m7GdFWHp5lVa5KtyI+CTV2jbotrgtAIz9eIAwW8J4Z+ESUBc63bhOnTnY6Zcegjp8U8TkBH6xTlRtS4zsSo5pGJt6QAQhwi8x9Lq5WD222i5pCR48c2FufEG//tPLTzrqz2x4i4hzCCuH1AQYKmkjpGbU9C01oeU4fFCoMPAbSmHIuvi7f6Y9nzMVYpQ3ij8mtFg4DThsmd9rrBqaeuB3WpRwm8bgMQ81KkFiQs85dbMl2Yu+7uL595x3UvN/ZEHP4JfRd7oY24Hh7vXfLYbVH+EXK01SThzhU+m9iNd3T7pxqUT3j74GxotYMEVc7+uG/tDJXNYxON2XqBa7fWYE+E+zXt3A2p89MUBzwa8FU/peYp7Qga4hmPhEJy60L2V56sIh9YD01vTngtPhIQ3ls73FWQcBHbjzkYk6KY8mUc4cjFX2D66jV/lUYfD25Lt4TNB9kb+Ue7Iw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
